project:
  type: website

website:
  title: "Sea Ice in Alaska"
  navbar:
    left:
      - text: "Alaskan Arctic"
        file: arctic.qmd
      - text: "Eastern Bering"
        file: ebering.qmd
      - text: "Northern Bering"
        file: nbering.qmd
      - text: "ShinyFIN (SST)"
        href: https://shinyfin.psmfc.org/ak-sst-mhw/

      - text: "PolarWatch"
        href: https://polarwatch.noaa.gov

format:
  html:
    theme: flatly
    css: styles.css
    toc: true

editor: visual

